config/routes.rb
Rails.application.routes.draw do
  get 'home/index'


  devise_for :users
  root to: "home#index"
  resources :articulos
  resources :categorias
  resources :tallas
  resources :especialidades

  resources :users, only: [:edit,:update] do
  resources :cursos, only: [:index], module: :users
  end

  resources :categorias do
  resources :articulos, module: :categorias, only: [:index]
  end

end

app/models/categoria.rb
class Categoria < ApplicationRecord
  validates :nombre , presence: true, uniqueness: true
  has_many :articulos
  mount_uploader :foto, AvatarUploader
end

app/controllers/categorias/articulos_controller.rb
class Categorias::ArticulosController < ApplicationController
  before_action :inicial
    #GET /articulos
  def index
    @articulos = @categoria.articulos.page params[:page]
    if params[:q].present?
      @articulos = @categoria.articulos.where("nombre ilike :q or codigo::varchar(255) ilike :q", q: "%#{params[:q]}%").page params[:page]
    end
  end
  private
  def inicial
    @categoria = Categoria.find(params[:categoria_id])
  end
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController

  before_action :authenticate_user!, except: [:index]
  before_action :authenticate_role_user, except: [:index]

  respond_to :html
  #GET /categorias
  def index
    @categorias = Categoria.all
    if params[:q].present?
      @categorias = @categorias.where("nombre ilike :q", q: "%#{params[:q]}%")
    end
  end
  #GET /categorias/:id
  def show
    @categoria = Categoria.find(params[:id])
  end
  #GET /categorias/new
  def new
    @categoria = Categoria.new
  end
  def edit
    @categoria = Categoria.find(params[:id])
  end

  #POST /categorias
  def create
    @categoria = Categoria.new(categoria_params)
    if @categoria.save!
      flash[:success] = "Categoria registrada correctamente"
      respond_with @categoria
    else
      flash[:alert] = "Problemas con la grabación"
      render :new
    end
  end
  #PUT /categorias/:id
  def update
    if @user.has_role? :admin
      @categoria = Categoria.find_by id: params[:id]
      if @categoria.update(categoria_params)
        flash[:success]="Categoria actualizada"
        respond_with @categoria
      else
        flash[:alert]="Error al actualizar"
        render :edit
      end
    else
      flash[:alert]="No tiene permisos para acceder a esa vista"
      render :edit
    end
  end

  private
  def categoria_params
    params.require(:categoria).permit(:nombre, :foto)
  end

  def authenticate_role_user
    @user = User.find(current_user.id)
    if @user.has_role? :admin
    else
      flash[:alert]="No tiene permisos para acceder a esa vista"
      redirect_to categorias_path(@categoria)
    end
  end
end

app/views/categorias/_form.html.erb
<div class="conta">
<div class="row">
  <div class="col-md-12">
    <div class="col-md-3">
    </div>
    <div class="col-md-5">
      <%= simple_form_for @categoria, html: { class: 'form-horizontal' } do |f| %>
      <div class="row">
        <div class="col-md-12">
            <%= f.input :nombre, class: "form-control" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
            <%= f.input :foto, input_html: {class: "form-control input-lg"} %>
        </div>
      </div><br>
        <div class="row">
          <div class="col-md-4">
          </div>
          <div class="col-md-4">
              <%= f.submit "Guardar Cambios", class:"btn btn-nar" %>
          </div>
          <div class="col-md-4">
          </div>
        </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">
    </div>
  </div>
</div>

app/views/categorias/edit.html.erb
<div class="container">
  <% breadcrumb :categoria_edit, @categoria %>
  <div class="row">
    <div class="col-md-11">
      <h1 class="text-center">Editar Categoria: "<%=@categoria.nombre%>"</h1><br><br>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/categorias/index.html.erb
<div class="container">
  <div class="row">
    <% if signed_in? %>
      <% breadcrumb :categorias %>
        <% if current_user.has_role? :admin %>
          <div class="table-responsive">
            <h1 class="text-center">Categorias</h1>
            <%= form_tag(categorias_path, class:"form-inline" , method: :get) do %>
              <div class="form-group">
                <input type="text" name="q" class="form-control" placeholder="Buscar..." type="text" value="<%= params[:q] %>">
                <span class="form-group-btn">
                  <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
              </div>
             <%end%><br>
                <div class="col-md-10">
                  <table class="table table-striped table-bordered">
                    <tr>
                      <th class="bg-light">ID</th>
                      <th class="bg-light">NOMBRE</th>
                    </tr>
                    <% @categorias.each do |categoria| %>
                      <tr>
                        <td><%= categoria.id %></td>
                        <td><%= link_to categoria.nombre, categoria_articulos_path(categoria.id)%></td>
                    <%end%>
                      </tr>
                      <% unless @categorias.present? %>
                        <tr>
                          <h2 class="text-center">No Hay Informacion Solicitada</h2>
                        </tr>
                      <%end%>
                  </table>
                  </div>
                  <div class="col-md-2">
                  </div>
              </div>
            <%else%>
                  <% breadcrumb :categorias %>
                    <h1 class="text-center">Categorias</h1>

                        <% @categorias.each do |categoria| %>
                        <div class="col">
                           <%= link_to categoria_path(categoria) do %>
                              <div class="full-width post">
                                <%= link_to categoria_articulos_path(categoria.id) do %>
                                  <figure class="full-width post-img">
                                    <!-- Tamaño de la imagen 248x186 pixeles-->
                                    <% if categoria.foto.present? %>
                                        <%= image_tag categoria.foto.thumb.url%>
                                    <%else%>
                                        <%= image_tag 'logoSena.png'%>
                                    <%end%>
                                  </figure>
                                <%end%>
                                <div class="full-width post-info">
                                   <p class="full-width post-info-price nom_gru"><%= link_to categoria.nombre, categoria_articulos_path(categoria.id)%></p>
                                </div>
                              </div>
                      </div>
                    <%end%>
              <%end%>
          <%end%>
    <%end%>
  </div>
</div>

app/views/categorias/new.html.erb
<% breadcrumb :categoria_new %>
<div class="container">
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
      <h1>Registar Categoria</h1>
    </div>
    <div class="col-md-4">
    </div>
  </div>
  <%= render "form" %>
</div>

app/views/categorias/show.html.erb
<% breadcrumb :categoria_show, @categoria %>
<div class="container">
  <div class="col-md-12">
     <h1 class="text-center">Categoria: "<%= @categoria.nombre%>"</h1>
        <div class="row">
           <div class="col-md-2"></div>
              <div class="col-md-8">
                 <table class="table table-striped">
                    <tr>
                      <th class="active">Nombre</th>
                      <th class="active">Editar</th>
                    </tr>
                    <tr>
                      <td class=""><h3><%= @categoria.nombre %></h3></td><br>
                      <td><%= link_to "Editar", edit_categoria_path(@categoria) , class:"btn btn-nar"%> </td>
                    </tr>
                </table>
              </div>
              <div class="col-md-2"></div>
          </div>
    </div>
</div>