config/routes.rb
Rails.application.routes.draw do
  get 'home/index'


  devise_for :users
  root to: "home#index"
  resources :articulos
  resources :categorias
  resources :tallas
  resources :especialidades

  resources :users, only: [:edit,:update] do
  resources :cursos, only: [:index], module: :users
  end

  resources :categorias do
  resources :articulos, module: :categorias, only: [:index]
  end

end

app/models/articulo.rb
class Articulo < ApplicationRecord
    validates :nombre , presence: true, uniqueness: true
    validates :cantidad , presence: true
    validates :valor , presence: true
    validates :codigo, presence: true

    belongs_to :categoria
    #belongs_to :especialidad
    #belongs_to :talla
    mount_uploader :imagen, ImagenUploader
end

app/models/categoria.rb
class Categoria < ApplicationRecord
  validates :nombre , presence: true, uniqueness: true
  has_many :articulos
  mount_uploader :foto, AvatarUploader
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :authenticate_role_user, except: [:index, :show]

  respond_to :html
  #GET /articulos
  def index
    @articulos = Articulo.all.page params[:page]
    if params[:q].present?
      @articulos = @articulos.where("nombre ilike :q or codigo::varchar(255) ilike :q", q: "%#{params[:q]}%").page params[:page]
    end
  end
  #GET /articlos/:id
  def show
    @articulo = Articulo.find(params[:id])
  end
  #GET /articulos/new
  def new
    @articulo = Articulo.new
  end
  def edit
    @articulo = Articulo.find(params[:id])
  end
  #POST /articulos
  def create
        @articulo = Articulo.new(articulo_params)
    if @articulo.save!
      flash[:success] = "Articulo registrado correctamente"
      respond_with @articulo
    else
      flash[:alert] = "Problemas con la grabación"
      render :new
    end
  end
  #PUT /articulos/:id
  def update
    if @user.has_role? :admin
      @articulo = Articulo.find_by id: params[:id]
      if @articulo.update(articulo_params)
        flash[:success]="Articulo actualizado"
        respond_with @articulo
      else
          flash[:alert]="Error al actualizar el Articulo (Verifique los campos)"
        render :edit
      end
    else
      flash[:alert]="No tiene permisos para acceder a esa vista"
      render :edit
    end
  end
  #DELETE /articulos/:id
  def destroy
    @articulo = Articulo.find(params[:id]).destroy
    flash[:success] = "Articulo Eliminado"
    redirect_to articulos_path
  end

  private
  def articulo_params
    params.require(:articulo).permit(:nombre,:estado , :cantidad,:valor,:codigo,:categoria_id,:imagen)
  end

  def authenticate_role_user
    @user = User.find(current_user.id)
    if @user.has_role? :admin
    else
      flash[:alert]="No tiene permisos para acceder a esa vista"
      redirect_to articulos_path(@articulo)
    end
  end
end

app/controllers/categorias/articulos_controller.rb
class Categorias::ArticulosController < ApplicationController
  before_action :inicial
    #GET /articulos
  def index
    @articulos = @categoria.articulos.page params[:page]
    if params[:q].present?
      @articulos = @categoria.articulos.where("nombre ilike :q or codigo::varchar(255) ilike :q", q: "%#{params[:q]}%").page params[:page]
    end
  end
  private
  def inicial
    @categoria = Categoria.find(params[:categoria_id])
  end
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController

  before_action :authenticate_user!, except: [:index]
  before_action :authenticate_role_user, except: [:index]

  respond_to :html
  #GET /categorias
  def index
    @categorias = Categoria.all
    if params[:q].present?
      @categorias = @categorias.where("nombre ilike :q", q: "%#{params[:q]}%")
    end
  end
  #GET /categorias/:id
  def show
    @categoria = Categoria.find(params[:id])
  end
  #GET /categorias/new
  def new
    @categoria = Categoria.new
  end
  def edit
    @categoria = Categoria.find(params[:id])
  end

  #POST /categorias
  def create
    @categoria = Categoria.new(categoria_params)
    if @categoria.save!
      flash[:success] = "Categoria registrada correctamente"
      respond_with @categoria
    else
      flash[:alert] = "Problemas con la grabación"
      render :new
    end
  end
  #PUT /categorias/:id
  def update
    if @user.has_role? :admin
      @categoria = Categoria.find_by id: params[:id]
      if @categoria.update(categoria_params)
        flash[:success]="Categoria actualizada"
        respond_with @categoria
      else
        flash[:alert]="Error al actualizar"
        render :edit
      end
    else
      flash[:alert]="No tiene permisos para acceder a esa vista"
      render :edit
    end
  end

  private
  def categoria_params
    params.require(:categoria).permit(:nombre, :foto)
  end

  def authenticate_role_user
    @user = User.find(current_user.id)
    if @user.has_role? :admin
    else
      flash[:alert]="No tiene permisos para acceder a esa vista"
      redirect_to categorias_path(@categoria)
    end
  end
end

app/helpers/articulo_helper.rb
module ArticuloHelper

  def mostrar_nose(f)
    if params[:action] == 'edit'
      f.input :estado, as: :radio_buttons, collection: [['Activo',true],['Inactivo', false]]
    else
      nil
    end
  end
end

app/views/categorias/articulos/index.html.erb
<div class="container">
  <div class="row">
  <% breadcrumb :categoria_articulos, @categoria, @articulos %>
  <h1 class="text-center">Articulos De La Categorias <b><%= @categoria.nombre %></b> </h1>
  <% if signed_in? %>
    <%if current_user.has_role? :admin %>
      <div class="table-responsive">
        <%= form_tag(categoria_articulos_path, class:"form-inline" , method: :get) do %>
          <div class="form-group">
            <input type="text" name="q" class="form-control" placeholder="Buscar..." type="text" value="<%= params[:q] %>">
            <span class="form-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
            </span>
          </div>
        <%end%><br>
            <table class="table table-striped table-bordered">
              <tr>
                <th class="bg-primary">ID</th>
                <th class="bg-primary">CODIGO</th>
                <th class="bg-primary">NOMBRE</th>
                <th class="bg-primary">CANTIDAD</th>
                <th class="bg-primary">PRECIO</th>
                <th class="bg-primary">ESTADO</th>
              </tr>
              <% @articulos.each do |articulo| %>
                <tr>
                  <td><%=  articulo.id%></td>
                  <td><%= link_to articulo.codigo , articulo_path(articulo.id) %></td>
                  <td><%=  articulo.nombre %></td>
                  <td><%=  articulo.cantidad %></td>
                  <td><%=  articulo.valor %></td>
                  <td><%= articulo.estado ? "Activo" : "Inactivo" %></td>
                </tr>
              <%end%>
              <% unless @articulos.present? %>
                <tr>
                  <h2 class="text-center">No Hay Informacion Solicitada</h2>
                </tr>
              <%end%>
            </table>
      </div><br>
        <%else%>
        <% breadcrumb :categoria_articulos, @categoria, @articulos %>
         <% @articulos.each do |articulo| %>
           <div class="col">
             <%= link_to articulo_path(articulo.id) do %>
                <div class="full-width post">
                   <figure class="full-width post-img">
                   <!-- Tamaño de la imagen 248x186 pixeles-->
                      <% if articulo.imagen.present? %>
                        <%= image_tag articulo.imagen.thumb.url %>
                      <%else%>
                        <%= image_tag 'default-150x150'%>
                      <%end%>
                      <div class="full-width post-info">
                        <p class="full-width post-info-price nom_gru"><label>Nombre: </label><%=  articulo.nombre%></p>
                        <p class="full-width post-info-price nom_gru"><label>Precio: </label><%=  articulo.valor%></p>
                      </div>
                    </figure>
                 </div>
              <%end%>
           </div>
         <%end%>
    <%end%>
  <%end%>
  </div>
  <div class="text-left">
    <%= paginate @articulos, :theme => 'twitter-bootstrap-3',:pagination_class => "pagination-sm" %>
  </div>
</div>