config/routes.rb
Rails.application.routes.draw do
  get 'home/index'


  devise_for :users
  root to: "home#index"
  resources :articulos
  resources :categorias
  resources :tallas
  resources :especialidades

  resources :users, only: [:edit,:update] do
  resources :cursos, only: [:index], module: :users
  end

  resources :categorias do
  resources :articulos, module: :categorias, only: [:index]
  end

end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 2.4.18
  </div>
  <strong>Copyright &copy; 2014-2019 <a class= "navegatt" href="https://adminlte.io">AdminLTE</a>.</strong> All rights reserved.
</footer>

app/views/layouts/_navegation.html.erb
<header class="main-header">
  <a href="<%=home_index_path%>" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>U</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>UNIFOR</b>MATE</span>
  </a>
  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
           <li class="dropdown user user-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <% if current_user.perfil.thumb.present?%>
                        <%= image_tag current_user.perfil.thumb,  class: "user-image", alt: "User Image"%>
                      <%else%>
                        <%=image_tag 'user2-160x160.jpg', class: "user-image", alt: "User Image"%>
                      <%end%>
                          <% if user_signed_in? %>
                          <span class="hidden-xs"><%= current_user.nombre.upcase%></span>
                        </a>
                    <%end%>
                    <ul class="dropdown-menu">
                      <li class="user-header">
                        <% if current_user.perfil.thumb.present?%>
                          <%= image_tag current_user.perfil.thumb,  class: "img-circle", alt: "User Image"%>
                        <%else%>
                          <%=image_tag 'user2-160x160.jpg', class: "img-circle", alt: "User Image"%>
                        <%end%>
                        <% if user_signed_in? %>
                        <p>
                          <%= current_user.nombre.upcase%>
                          <small>Miembro desde: <%= l current_user.created_at, format: :long%></small>
                        </p>
                      </li>
                      <%end%>
                      <!-- Menu Body -->
                      <li class="user-body">
                        <div class="row">
                          <div class="col-xs-4 text-center">
                            <a href="#"></a>
                          </div>
                          <div class="col-xs-4 text-center">
                            <a href="#"></a>
                          </div>
                          <div class="col-xs-4 text-center">
                            <a href="#"></a>
                          </div>
                        </div>
                        <!-- /.row -->
                      </li>
                      <!-- Menu Footer-->
                      <li class="user-footer">
                        <div class="pull-left">
                          <a href="<%= edit_user_registration_path %>" class="btn btn-nar">MI PERFIL</a>
                        </div>
                        <div class="pull-right">
                          <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete, class: "btn btn-danger header-menu-mobile-btn"%>
                        </div>
                      </li>
                    </ul>
                  </li>
                <% else %>
                <li class="dropdown messages-menu">
                  <a href="<%= new_user_session_path %>"><span class="fa fa-user-circle-o"></span>INICIAR SESIÓN</a>
                </li>
                <li class="dropdown notifications-menu">
                  <a href="<%=new_user_registration_path%>"><span class="fa fa-registered"></span>REGISTRARME</a>
                </li>
          <% end %>
        <!-- Control Sidebar Toggle Button -->
      </ul>
    </div>
  </nav>
</header>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <% if current_user.perfil.thumb.present?%>
          <%= image_tag current_user.perfil.thumb,  class: "img-circle", alt: "img-circle"%>
        <%else%>
          <%=image_tag 'user2-160x160.jpg', class: "img-circle", alt: "User Image"%>
        <%end%>
      </div>
      <div class="pull-left info">
        <small><%= current_user.nombre.upcase%></small><br>
        <a href="#"><i class="fa fa-circle text-success"></i>Online</a>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">MENU DE NAVEGACION</li>
      <li class="active treeview menu-open">
        <a href="#">
          <i class="fa fa-dashboard"></i> <span>Articulos</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="<%=articulos_path%>"><i class="fa fa-circle-o"></i>Lista de Articulos</a></li>
            <% if current_user.has_role? :admin%>
              <li class="active"><a href="<%=new_articulo_path%>"><i class="fa fa-circle-o"></i>Crear Articulo</a></li>
            <%end%>
        </ul>
      </li>
      <% if current_user.has_role? :admin%>
      <li class="active treeview menu-open">
        <a href="#">
          <i class="fa fa-dashboard"></i> <span>Categorias</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="<%=categorias_path%>"><i class="fa fa-circle-o"></i>Lista de Categorias</a></li>
          <li class="active"><a href="<%=new_categoria_path%>"><i class="fa fa-circle-o"></i>Crear Categorias</a></li>
        </ul>
        <%end%>
      </li>
      <% if current_user.has_role? :admin%>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-dashboard"></i> <span>Especialidades</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="<%=especialidades_path%>"><i class="fa fa-circle-o"></i> Listado De Especialidades</a></li>
            <li><a href="<%=new_especialidad_path%>"><i class="fa fa-circle-o"></i> Crear Especialidad</a></li>
        </ul>
      </li>
      <%end%>
      <% if current_user.has_role? :admin%>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i>
            <span>Tallas</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="<%=tallas_path%>"><i class="fa fa-circle-o"></i> Listado De Tallas</a></li>
            <li><a href="<%=new_talla_path%>"><i class="fa fa-circle-o"></i> Crear Talla</a></li>
          </ul>
        </li>
      <%end%>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>
<!-- Content Wrapper. Contains page content -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>UNIFORMATE | V 1.0</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css")%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Main -->
    <%= stylesheet_link_tag  'main.css'%>
    <!--toastr -->
    <%= stylesheet_link_tag  'toastr/toastr.min.css'%>
    <!-- Bootstrap 3.3.7 -->
    <%= stylesheet_link_tag  'bootstrap/bootstrap.min.css'%>
    <!-- Font Awesome -->
    <%= stylesheet_link_tag  'bootstrap/font-awesome.min.css'%>
    <!-- Ionicons -->
    <%= stylesheet_link_tag  'bootstrap/ionicons.min.css'%>
    <!-- jvectormap -->
    <%= stylesheet_link_tag  'bootstrap/jquery-jvectormap.css'%>
    <!-- Theme style -->
    <%= stylesheet_link_tag  'adminlte/adminlte.min.css'%>
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <%= stylesheet_link_tag  'adminlte/_all-skins.min.css'%>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
      <%= render "layouts/navegation" %>
      <div class="content-wrapper">
        <section class="content-header">
          <h1>Uniformate<small>Version 1.0</small></h1>
        </section>
        <section class="down">
          <%= breadcrumbs display_single_fragment: true, style: :bootstrap %>
        </section>
        <div class="container">
          <%= custom_bootstrap_flash %>
          <%=yield%>
        </div>
        <div class="control-sidebar-bg"></div>
      </div>
      <%= render "layouts/footer" %>
    <script>
      var dummyContent = $('.dummy-content').children(),
        i;
      $('#add-content').click(function(e){
        e.preventDefault();
        if($(dummyContent[0]).is(":visible")){
          for(i=0;i<dummyContent.length;i++){
            $(dummyContent[i]).fadeOut(600);
          }
        }
        else{
          for(i=0;i<dummyContent.length;i++){
            $(dummyContent[i]).delay(600*i).fadeIn(600);
          }
        }
      });
    </script>
    <!-- jQuery 3 -->
    <%= javascript_include_tag 'dist/js/jquery.min.js'%>
    <!-- Bootstrap 3.3.7 -->
    <%= javascript_include_tag 'dist/js/bootstrap.min.js'%>
    <!-- FastClick -->
    <%= javascript_include_tag 'dist/js/fastclick.js'%>
    <!-- AdminLTE App -->
    <%= javascript_include_tag 'dist/js/adminlte.min.js'%>
    <!-- Sparkline -->
    <%= javascript_include_tag 'dist/js/jquery.sparkline.min.js'%>
    <!-- jvectormap  -->
    <%= javascript_include_tag 'dist/plugins/jquery-jvectormap-1.2.2.min.js'%>
    <%= javascript_include_tag 'dist/plugins/jquery-jvectormap-world-mill-en.js'%>
    <!-- SlimScroll -->
    <%= javascript_include_tag 'dist/js/jquery.slimscroll.min.js'%>
    <!-- ChartJS -->
    <%= javascript_include_tag 'dist/js/Chart.js'%>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <%= javascript_include_tag 'dist/js/dashboard2.js'%>
    <!-- AdminLTE for demo purposes -->
    <%= javascript_include_tag 'dist/js/demo.js'%>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>UNIFORMATE | V 1.0</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css")%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Main -->
    <%= stylesheet_link_tag  'main.css'%>
    <!--toastr -->
    <%= stylesheet_link_tag  'toastr/toastr.min.css'%>
    <!-- Bootstrap 3.3.7 -->
    <%= stylesheet_link_tag  'bootstrap/bootstrap.min.css'%>
    <!-- Font Awesome -->
    <%= stylesheet_link_tag  'bootstrap/font-awesome.min.css'%>
    <!-- Ionicons -->
    <%= stylesheet_link_tag  'bootstrap/ionicons.min.css'%>
    <!-- jvectormap -->
    <%= stylesheet_link_tag  'bootstrap/jquery-jvectormap.css'%>
    <!-- Theme style -->
    <%= stylesheet_link_tag  'adminlte/adminlte.min.css'%>
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <%= stylesheet_link_tag  'adminlte/_all-skins.min.css'%>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <header class="main-header">
      <!-- Logo -->
      <a href="<%=home_index_path%>" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>V</b>1.0</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>UNIFOR</b>MATE</span>
      </a>
      <!-- Header Navbar: style can be found in header.less -->
      <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
        <% if user_signed_in? %>
            <% if current_user.has_role? :admin %>
            <li class="dropdown messages-menu">
              <a href="<%=articulos_path%>"><span class="fa fa-user-circle-o"></span>ADMINISTRACION</a>
            </li>
          <%else%>
          <li class="dropdown notifications-menu">
            <a href="<%=categorias_path%>">
              <i class="fas fa-tools"></i>
              <span></span>ARTICULOS
            </a>
          </li>
          <%end%>
        <%end%>
          <% if user_signed_in? %>
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <% if current_user.perfil.thumb.present?%>
              <%= image_tag current_user.perfil.thumb,  class: "user-image", alt: "User Image"%>
            <%else%>
            <%=image_tag 'user2-160x160.jpg', class: "user-image", alt: "User Image"%>
            <%end%>
                <% if user_signed_in? %>
                <span class="hidden-xs"><%= current_user.nombre.upcase%></span>
              </a>
              <%end%>
              <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header">
                  <% if current_user.perfil.thumb.present?%>
                    <%= image_tag current_user.perfil.thumb,  class: "img-circle", alt: "User Image"%>
                  <%else%>
                    <%=image_tag 'user2-160x160.jpg', class: "img-circle", alt: "img-circle"%>
                  <%end%>
                  <% if user_signed_in? %>
                  <p>
                    <%= current_user.nombre.upcase%>
                    <small>Miembro desde: <%= l current_user.created_at, format: :long%></small>
                  </p>
                </li>
                <%end%>
                <!-- Menu Body -->
                <li class="user-body">
                  <div class="row">
                    <div class="col-xs-4 text-center">
                      <a href="#">Followers</a>
                    </div>
                    <div class="col-xs-4 text-center">
                      <a href="#">Sales</a>
                    </div>
                    <div class="col-xs-4 text-center">
                      <a href="#">Friends</a>
                    </div>
                  </div>
                  <!-- /.row -->
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                  <div class="pull-left">
                    <a href="<%= edit_user_registration_path %>" class="btn btn-success">Editar Perfil</a>
                  </div>
                  <div class="pull-right">
                    <%= link_to "Salir", destroy_user_session_path, method: :delete, class: "btn btn-danger header-menu-mobile-btn"%>
                  </div>
                </li>
              </ul>
            </li>
          <% else %>
          <li class="dropdown messages-menu">
            <a href="<%= new_user_session_path %>">
            <span class="fa fa-user-circle-o"></span>  INICIAR SESIÓN
            </a>
          </li>
          <li class="dropdown notifications-menu">
            <a href="<%=new_user_registration_path%>">
              <span class="fa fa-registered"></span>REGISTRARME
            </a>
          </li>
  <% end %>
            <!-- Control Sidebar Toggle Button -->
          </ul>
        </div>
      </nav>
    </header>
      <div class="container">
        <%= custom_bootstrap_flash %>
        <%=yield%>
      </div>
  <!-- jQuery 3 -->
  <%= javascript_include_tag 'dist/js/jquery.min.js'%>
  <!-- Bootstrap 3.3.7 -->
  <%= javascript_include_tag 'dist/js/bootstrap.min.js'%>
  <!-- FastClick -->
  <%= javascript_include_tag 'dist/js/fastclick.js'%>
  <!-- AdminLTE App -->
  <%= javascript_include_tag 'dist/js/adminlte.min.js'%>
  <!-- Sparkline -->
  <%= javascript_include_tag 'dist/js/jquery.sparkline.min.js'%>
  <!-- jvectormap  -->
  <%= javascript_include_tag 'dist/plugins/jquery-jvectormap-1.2.2.min.js'%>
  <%= javascript_include_tag 'dist/plugins/jquery-jvectormap-world-mill-en.js'%>
  <!-- SlimScroll -->
  <%= javascript_include_tag 'dist/js/jquery.slimscroll.min.js'%>
  <!-- ChartJS -->
  <%= javascript_include_tag 'dist/js/Chart.js'%>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <%= javascript_include_tag 'dist/js/dashboard2.js'%>
  <!-- AdminLTE for demo purposes -->
  <%= javascript_include_tag 'dist/js/demo.js'%>

  <!--<footer class="full-width footer">
    <div class="full-width">
      <b>Version</b> 2.4.18
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE</a>.</strong> All rights
    reserved.
  </footer>-->

  </body>
</html>