config/routes.rb
Rails.application.routes.draw do
  get 'home/index'


  devise_for :users
  root to: "home#index"
  resources :articulos
  resources :categorias
  resources :tallas
  resources :especialidades

  resources :users, only: [:edit,:update] do
  resources :cursos, only: [:index], module: :users
  end

  resources :categorias do
  resources :articulos, module: :categorias, only: [:index]
  end

end

app/models/articulo.rb
class Articulo < ApplicationRecord
    validates :nombre , presence: true, uniqueness: true
    validates :cantidad , presence: true
    validates :valor , presence: true
    validates :codigo, presence: true

    belongs_to :categoria
    #belongs_to :especialidad
    #belongs_to :talla
    mount_uploader :imagen, ImagenUploader
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :authenticate_role_user, except: [:index, :show]

  respond_to :html
  #GET /articulos
  def index
    @articulos = Articulo.all.page params[:page]
    if params[:q].present?
      @articulos = @articulos.where("nombre ilike :q or codigo::varchar(255) ilike :q", q: "%#{params[:q]}%").page params[:page]
    end
  end
  #GET /articlos/:id
  def show
    @articulo = Articulo.find(params[:id])
  end
  #GET /articulos/new
  def new
    @articulo = Articulo.new
  end
  def edit
    @articulo = Articulo.find(params[:id])
  end
  #POST /articulos
  def create
        @articulo = Articulo.new(articulo_params)
    if @articulo.save!
      flash[:success] = "Articulo registrado correctamente"
      respond_with @articulo
    else
      flash[:alert] = "Problemas con la grabación"
      render :new
    end
  end
  #PUT /articulos/:id
  def update
    if @user.has_role? :admin
      @articulo = Articulo.find_by id: params[:id]
      if @articulo.update(articulo_params)
        flash[:success]="Articulo actualizado"
        respond_with @articulo
      else
          flash[:alert]="Error al actualizar el Articulo (Verifique los campos)"
        render :edit
      end
    else
      flash[:alert]="No tiene permisos para acceder a esa vista"
      render :edit
    end
  end
  #DELETE /articulos/:id
  def destroy
    @articulo = Articulo.find(params[:id]).destroy
    flash[:success] = "Articulo Eliminado"
    redirect_to articulos_path
  end

  private
  def articulo_params
    params.require(:articulo).permit(:nombre,:estado , :cantidad,:valor,:codigo,:categoria_id,:imagen)
  end

  def authenticate_role_user
    @user = User.find(current_user.id)
    if @user.has_role? :admin
    else
      flash[:alert]="No tiene permisos para acceder a esa vista"
      redirect_to articulos_path(@articulo)
    end
  end
end

app/controllers/categorias/articulos_controller.rb
class Categorias::ArticulosController < ApplicationController
  before_action :inicial
    #GET /articulos
  def index
    @articulos = @categoria.articulos.page params[:page]
    if params[:q].present?
      @articulos = @categoria.articulos.where("nombre ilike :q or codigo::varchar(255) ilike :q", q: "%#{params[:q]}%").page params[:page]
    end
  end
  private
  def inicial
    @categoria = Categoria.find(params[:categoria_id])
  end
end

app/helpers/articulo_helper.rb
module ArticuloHelper

  def mostrar_nose(f)
    if params[:action] == 'edit'
      f.input :estado, as: :radio_buttons, collection: [['Activo',true],['Inactivo', false]]
    else
      nil
    end
  end
end

app/views/articulos/_form.html.erb
<div class="container">
  <div class = "row">
      <div class="col-md-12">
        <%= simple_form_for(@articulo) do |f| %>
          <% @articulo.errors.full_messages.each do |message| %>
            <div class="form-group text-center be-red white">
            <%= message %>
            </div>
          <%end%>
            <div class="row">
              <div class="col-md-5">
                <label>Nombre</label>
                <%= f.text_field :nombre, required: true,autofocus: true, class:"form-control", placeholder: "Nombre del Articulo"%>
              </div>
              <div class="col-md-5">
                <label>Codigo</label>
                <%= f.number_field :codigo, required: true,autofocus: true, min:1,class: 'form-control', placeholder: "Codigo del Articulo"%>
              </div>
            </div><br>
            <div class="row">
              <div class="col-md-5">
                <label>Cantidad</label>
                    <%= f.number_field :cantidad,required: true, autofocus: true, min:1, class:"form-control", placeholder: "Escribe La Cantidad De articulo"%>
              </div>
              <div class="col-md-5">
                <label>Valor (Precio $)</label>
                <%= f.number_field :valor,required: true,autofocus: true, min:1 , class: "form-control", placeholder: "Escribe el valor Del articulo", hint: "Escriba el valor del Articulo sin puntos ni comas."%>
              </div>
            </div><br>
            <div class="row">
              <div class="col-md-5">
                  <%= f.association :categoria, label_method: :nombre, value_method: :id, min:"1"%>
              </div>
              <div class="col-md-5">
                <%= f.input :imagen, input_html: {class: "form-control input-lg"}%>
              </div>
            </div>
            <div class="row">
              <div class="col-md-5">
                <%= mostrar_nose(f) %>
              </div>
            </div>
            <div class="row">
              <div class="from-group">
                <%= f.submit "Guardar Cambios", class:"btn btn-nar" %>
              </div>
            </div>
        <%end%>
      </div>
   </div>
</div>

app/views/articulos/edit.html.erb
<div class="container">
  <% breadcrumb :articulo_edit, @articulo %>
  <h1 class="text-center">Editar<%=@articulo.nombre %></h1>
  <%= render "form" %>
</div>

app/views/articulos/index.html.erb
<div class="container">
  <div class="row">
    <% if signed_in? %>
      <% breadcrumb :articulos %>
      <%if current_user.has_role? :admin %>
        <div class="table-responsive">
            <h1 class="text-center">Articulos</h1>
          <%= form_tag(articulos_path, class:"form-inline" , method: :get) do %>
            <div class="form-group">
              <input type="text" name="q" class="form-control" placeholder="Buscar..." type="text" value="<%= params[:q] %>">
              <span class="form-group-btn">
                  <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          <%end%>
              <br><table class="table table-striped table-bordered">
                <tr>
                  <th class="bg-primary">ID</th>
                  <th class="bg-primary">CODIGO</th>
                  <th class="bg-primary">NOMBRE</th>
                  <th class="bg-primary">CANTIDAD</th>
                  <th class="bg-primary">PRECIO</th>
                  <th class="bg-primary">ESTADO</th>
                </tr>
                <% @articulos.each do |articulo| %>
                  <tr>
                    <td><%=  articulo.id%></td>
                    <td><%= link_to articulo.codigo , articulo_path(articulo.id) , :remote=>true  %></td>
                    <td><%=  articulo.nombre %></td>
                    <td><%=  articulo.cantidad %></td>
                    <td><%=  articulo.valor %></td>
                    <td><%= articulo.estado ? "Activo" : "Inactivo" %></td>
                  </tr>
                <%end%>
                <% unless @articulos.present? %>
                  <tr>
                    <h2 class="text-center">No Hay Informacion Solicitada</h2>
                  </tr>
                <%end%>
              </table>
              <div id="new-articulo">
              </div>
        </div><br>
      <%else%>
         <% breadcrumb :articulos %>
          <h1 class="text-center">Articulos en Venta</h1>
          <%= form_tag(articulos_path, class:"form-inline" , method: :get) do %>
            <div class="form-group">
              <input type="text" name="q" class="form-control" placeholder="Buscar..." type="text" value="<%= params[:q] %>">
              <span class="form-group-btn">
                  <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          <%end%>
          <div class="col">
            <% @articulos.each do |articulo| %>
              <%= link_to articulo_path(articulo.id) do %>
                 <div class="full-width post">
                    <figure class="full-width post-img">
                    <!-- Tamaño de la imagen 248x186 pixeles-->
                       <% if articulo.imagen.present? %>
                         <%= image_tag articulo.imagen.thumb.url %>
                       <%else%>
                         <%= image_tag 'logoSena.png'%>
                       <%end%>
                       <div class="full-width post-info">
                          <p class="full-width post-info-price nom_gru"><label>Nombre: </label><%=  articulo.nombre%></p>
                         <p class="full-width post-info-price nom_gru"><label>Categoria: </label><%= articulo.categoria.nombre%></p>                                               
                       </div>
                     </figure>
                  </div>
               <%end%>
            <%end%>
            <% unless @articulos.present? %>
              <tr>
                <h2 class="text-center">No Hay Informacion Solicitada</h2>
              </tr>
            <%end%>
          </div>
      <%end%>
    <%end%>
  </div>
    <div class="text-left">
      <%= paginate @articulos, :theme => 'twitter-bootstrap-3',:pagination_class => "pagination-sm" %>
    </div>
</div>

app/views/articulos/new.html.erb
<% if signed_in?%>
  <% if current_user.has_role? :admin%>
      <div class="container">
        <% breadcrumb :articulos_new %>
          <h1 class="text-center">Crear Articulos</h1>
        <%= render "form" %>
    </div>
  <%end%>
  <%else%>
<%end%>

app/views/articulos/show.html.erb
<% if signed_in? %>
  <div class="col-md-1"></div>
     <div class="col-md-10">
       <% breadcrumb :articulo_show, @articulo %>
          <h1 class="text-center"><%= @articulo.nombre %></h1>
          <div class="form-group">
            <form>
              <div class="row">
                <div class="col-md-2">
                  <h2>Codigo</h2><%= @articulo.codigo%>
                    <%if current_user.has_role? :admin %>
                      <br><br><%= link_to "Editar Articulo", edit_articulo_path(@articulo) , class:"btn btn-nar"%><br><br>
                    <%end%>
                 </div>
                 <div class="col-md-2">
                    <h2>Nombre</h2>
                    <%= @articulo.nombre %>
                 </div>
                 <div class="col-md-2">
                     <h2>Cantidad </h2>
                     <%= @articulo.cantidad %>
                 </div>
                 <div class="col-md-2">
                     <h2>Precio</h2>
                     <%= @articulo.valor %>
                 </div>
                 <div class="col-md-2">
                     <h2>Categoria</h2>
                     <%= @articulo.categoria.nombre %>
                 </div>
                 <div class="col-md-2">
                      <h2>Estado</h2>
                      <%= @articulo.estado ? "Activo" : "Inactivo" %>
                 </div>
              </div><br>
            </form>
          </div>
      </div>
  <div class="col-md-1"></div>
<%end%>